version: '2.3'

services:
  notebook:
    image: tackman/jupyter-cuda
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
    networks:
      - default
    runtime: nvidia
    environment:
      - JUPYTER_ENABLE_LAB=yes

networks:
  default:
    driver: bridge
